// Social feature types

export enum SocialTemplateId {
  // Character-specific encounters (implemented)
  JOKESTER_ENCOUNTER = "JOKESTER_ENCOUNTER",
  RIDDLER_ENCOUNTER = "RIDDLER_ENCOUNTER",
  GOSSIP_MERCHANT = "GOSSIP_MERCHANT",

  // Standardized outcomes
  SOCIAL_SUCCESS = "SOCIAL_SUCCESS",
  SOCIAL_FAILURE = "SOCIAL_FAILURE",
  SOCIAL_NEUTRAL = "SOCIAL_NEUTRAL"
}

export enum SocialActionId {
  // Jokester actions
  LAUGH_AT_JOKE = "LAUGH_AT_JOKE",
  GROAN_AT_JOKE = "GROAN_AT_JOKE",
  TELL_JOKE = "TELL_JOKE",

  // Riddler actions
  THINK_ABOUT_RIDDLE = "THINK_ABOUT_RIDDLE",
  GIVE_UP_ON_RIDDLE = "GIVE_UP_ON_RIDDLE",
  ANSWER_RIDDLE = "ANSWER_RIDDLE",

  // Gossip merchant actions
  LISTEN_TO_GOSSIP = "LISTEN_TO_GOSSIP",
  REJECT_GOSSIP = "REJECT_GOSSIP",
  SHARE_GOSSIP = "SHARE_GOSSIP",

  // Hermit actions
  APOLOGIZE_TO_HERMIT = "APOLOGIZE_TO_HERMIT",
  DISMISS_HERMIT = "DISMISS_HERMIT",
  ASK_ABOUT_OLD_DAYS = "ASK_ABOUT_OLD_DAYS",

  // Universal action
  WALK_AWAY = "WALK_AWAY"
}